config/routes.rb
Rails.application.routes.draw do
 
  get 'static_pages/mononoaware'

  root 'welcome#index'

  
  resources :books
  resources :essences
  resources :words
  resources :events
  resources :texts
  resources :authors
  

end

app/models/author.rb
class Author < ActiveRecord::Base


	has_many :books



	private
    
    def author_params
      params.require(:author).permit(:name, :country, :years, :note)
    end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	before_filter :find_author,      only: [:show, :edit, :update, :destroy]
	# before_filter :check_if_admin, only: [:new, :edit, :create, :update, :destroy]



	def index
		@authors = Author.all
		# render text: @authors.map { |i| "#{i.russian}: --- #{i.greek} --- #{i.latin} --- #{i.english} --- #{i.french} --- #{i.german} --- #{i.dutch} --- #{i.spanish} --- #{i.italian} --- #{i.hungarian} --- #{i.croatian}  "   }.join("<br/>" )
	end

	def new
		@author = Author.new
	end

	def edit
	    # @author = Author.find(params[:id])	
	end

	def create

		@author = Author.new(author_params)

		respond_to do |format|
	      if @author.save
	        format.html { redirect_to @author, notice: 'Author was successfully created.' }
	        # format.json { render :show, status: :created, location: @author }
	        # format.json { render @author.to_json, status: :created }
	        format.json  { render :json => @author }

	      else
	        format.html { render :new }
	        format.json { render json: @author.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def show #R
		unless @author #= Author.where( id: params[:id] ).first
			render text: "Page not found", status: 404
		end
	end

	def update #U
		# @author = Author.find_by_id(params[:id])
		@author.update_attributes(author_params)
		if @author.errors.empty?
			redirect_to author_path(@author)
		else
			render "edit"
		end
	end

	def destroy #D
		# @author = Author.find(params[:id])
		@author.destroy
		redirect_to action: "index"
	end

	private 

	def author_params
		params.require(:author).permit(:name, :country, :years, :note)
	end

	def find_author
		@author = Author.find(params[:id])
	end

	# def check_if_admin
	# 	render text: "Access denied", status: 403 unless params[:admin]
	# end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
# _form.html.erb

<%= form_for @author, remote: true do |f|   %>
  <%= author.text_field  :name          %>
  <%= author.text_field  :country       %>
  <%= author.text_field  :year          %>
  <%= author.text_field  :note          %>
  <%= f.button :submit                  %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit</h1>

<%= form_for @author do |author| %>
    Имя -          <%= author.text_field :name %>
	Страна -       <%= author.text_field :country %>
	Годы -         <%= author.text_field :years %></br>
	Примечания -   <%= author.text_field :note %> 

    	
	<p><%= author.submit "Создать" %> </p>
<% end %>

    

app/views/authors/index.html.erb
<h1>Авторы</h1>

<span class = "createAction">Create new</span>

<%=  link_to "Добавить нового автора", new_author_path %> 

<div id="author-form" style="display:none;">
</div>

<% if @authors.empty? %>
   <b>Список пуст</b>
<% else %>
<table>
	<tr>
		<th>id</th>
		<th>name</th>
		<th>country</th>
		<th>year</th>
		<th>note</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
    
    <% @authors.each do  |author| %>

    <tr>
		<td><%= author.id %></td>
		<td><%= author.name %></td>
		<td><%= author.country %></td>
		<td><%= author.years %></td>
		<td><%= author.note %></td>
		<td><%= link_to "Destroy", author, method: :delete, data: { confirm: "Точно удалить?"} %></td>
		<td><%= link_to 'Edit', edit_author_path(author) %></td>
		<td><%= link_to 'Edit2',  "/authors/#{author.id}/edit" %></td> 
		<td><%= link_to 'Show', author_path(author) %></td>
		
        


	</tr>
	<% end %>

</table>

	<% end %>

app/views/authors/new.html.erb
<h1>Create new</h1>

<%= form_for @author do |author| %>
    Имя -     <%= author.text_field :name %>
	Годы -  <%= author.text_field :years %></br>
	Страна -       <%= author.text_field :country %> 
	Примечания -   <%= author.text_field :note %>

	<p><%= author.submit "Создать" %> </p>
<% end %>

     

app/views/authors/show.html.erb
<h1>Авторы</h1>

<p><h2><%= @author.name %><h2/></p>

<ul>
	<li>Имя -     <%= @author.name %></li>
	<li>Годы -  <%= @author.years %></li>
	<li>Страна -       <%= @author.country %> </li>
	<li>Примечания -   <%= @author.note %></li>

</ul>

<p><%=  link_to "Back to authors List", authors_path %></p>