config/routes.rb
Rails.application.routes.draw do
 
  get 'static_pages/mononoaware'

  root 'welcome#index'

  
  resources :books
  resources :essences
  resources :words
  resources :events
  resources :texts
  resources :authors
  

end

app/models/essence.rb
class Essence < ActiveRecord::Base
end

app/controllers/essences_controller.rb
class EssencesController < ApplicationController
	before_filter :find_essence,      only: [:show, :edit, :update, :destroy]
	# before_filter :check_if_admin, only: [:new, :edit, :create, :update, :destroy]


	def index
		@essences = Essence.all
		# render text: @essences.map { |i| "#{i.russian}: --- #{i.greek} --- #{i.latin} --- #{i.english} --- #{i.french} --- #{i.german} --- #{i.dutch} --- #{i.spanish} --- #{i.italian} --- #{i.hungarian} --- #{i.croatian}  "   }.join("<br/>" )
	end

	def new
		@essence = Essence.new
	end

	def edit
	    # @essence = Essence.find(params[:id])	
	end

	def create #C
		# render text: params.inspect
		@essence = Essence.create(essence_params)
		if @essence.errors.empty?
			redirect_to essence_path(@essence)
		else
			render "new"
		end
	end

	def show #R
		unless @essence #= Essence.where( id: params[:id] ).first
			render text: "Page not found", status: 404
		end
	end

	def update #U
		# @essence = Essence.find_by_id(params[:id])
		@essence.update_attributes(essence_params)
		if @essence.errors.empty?
			redirect_to essence_path(@essence)
		else
			render "edit"
		end
	end

	def destroy #D
		# @essence = Essence.find(params[:id])
		@essence.destroy
		redirect_to action: "index"
	end

	private 

	def essence_params
		params.require(:essence).permit(:name, :description, :image_url, :links)
	end

	def find_essence
		@essence = Essence.find(params[:id])
	end

	# def check_if_admin
	# 	render text: "Access denied", status: 403 unless params[:admin]
	# end
end

app/helpers/essences_helper.rb
module EssencesHelper
end

app/views/essences/edit.html.erb
<h1>Edit</h1>

<%= form_for @essence do |essence| %>
    Имя -      <%= essence.text_field :name %>
	Описание - <%= essence.text_field :description %>
	Картинка - <%= essence.text_field :image_url %>
	Ссылки -   <%= essence.text_field :links %>

	<p><%= essence.submit "Создать" %> </p>
<% end %>

    

app/views/essences/index.html.erb
<h1>Сущности</h1>
<p>«Не следует множить сущее без необходимости», Оккам, 1285—1349</p>

<p><%=  link_to "Create new", new_essence_path %></p>

<% if @essences.empty? %>
   <b>Список пуст</b>
<% else %>
<table>
	<tr>
		<th>id</th>
		<th>name</th>
		<th>description</th>
		<th>image_url</th>
		<th>links</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>
    
    <% @essences.each do  |essence| %>

    <tr>
		<td><%= essence.id %></td>
		<td><%= essence.name %></td>
		<td><%= essence.description %></td>
		<td><%= essence.image_url %></td>
		<td><%= essence.links %></td>
		<td><%= link_to "Destroy", essence, method: :delete, data: { confirm: "Точно удалить?"} %></td>
		<td><%= link_to 'Edit', edit_essence_path(essence) %></td>
		<td><%= link_to 'Edit2',  "/essences/#{essence.id}/edit" %></td> 
		<td><%= link_to 'Show', essence_path(essence) %></td>
		
        


	</tr>
	<% end %>

</table>

	<% end %>

app/views/essences/new.html.erb
<h1>Create new</h1>

<%= form_for @essence do |essence| %>
    Имя -         <%= essence.text_field :name %>
	Описание - <%= essence.text_field :description %>
	Рисунок -          <%= essence.text_field :image_url %>
	Ссылки -      <%= essence.text_field :links %></br>
	
	<p><%= essence.submit "Создать" %> </p>
<% end %>

    

app/views/essences/show.html.erb
<h1>Слова</h1>

<h2><%= @essence.name %><h2/>

<ul>
	<li>Имя -      <%= @essence.name %></li>
	<li>Описание - <%= @essence.description %></li>
	<li>Картинка - <%= @essence.image_url %></li>
	<li>Ссылки -   <%= @essence.links %></li>
</ul>

<p><%=  link_to "Back to List", essences_path %></p>